sudo: false
language: c
addons:
  apt:
    packages: valgrind
compiler:
  - clang
  - gcc
env:
  - FLAGS=
  - FLAGS=debug
script:
  - make $(echo $FLAGS)
  - test/do

cache: apt

notifications:
  irc:
    nick: tiny-rbtree
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
